// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBhl3vpd31muvbqQzD2iDr3LLgz9tzW8',
    appId: '1:951014818162:web:c207cffd1cda8eafdc5deb',
    messagingSenderId: '951014818162',
    projectId: 'cute--tinder',
    authDomain: 'cute--tinder.firebaseapp.com',
    storageBucket: 'cute--tinder.appspot.com',
    measurementId: 'G-4H6YKZ805Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaHeMMKASCf9afTV2LUD24ltBLzuzcg54',
    appId: '1:951014818162:android:fcedcbb306547e31dc5deb',
    messagingSenderId: '951014818162',
    projectId: 'cute--tinder',
    storageBucket: 'cute--tinder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn2pMjes_XFHsy_CLW6fQSYnuZIwpAKtk',
    appId: '1:951014818162:ios:c56206e5c2f7896ddc5deb',
    messagingSenderId: '951014818162',
    projectId: 'cute--tinder',
    storageBucket: 'cute--tinder.appspot.com',
    androidClientId: '951014818162-5kcrro9lmrpb9439f0648rnovha9nsh8.apps.googleusercontent.com',
    iosClientId: '951014818162-4dcfsrum72jvei3c1h1k0imvb3memk9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuteTinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn2pMjes_XFHsy_CLW6fQSYnuZIwpAKtk',
    appId: '1:951014818162:ios:c6cd385256daecf7dc5deb',
    messagingSenderId: '951014818162',
    projectId: 'cute--tinder',
    storageBucket: 'cute--tinder.appspot.com',
    androidClientId: '951014818162-5kcrro9lmrpb9439f0648rnovha9nsh8.apps.googleusercontent.com',
    iosClientId: '951014818162-r9pnce8gfq92t5kdsihkekgtcsrp9q6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuteTinder.RunnerTests',
  );
}
